server:
  port: 8002
spring:
  datasource:
    username: root
    password: 20030106dnd
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
     # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 20030106dnd    # ← 填你的 Redis 密码
      database: 0
  cloud:
    nacos:
      discovery:
        enabled: false