server:
  port: 8002
spring:
  application:
    name: short-link-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 20030106dnd    # ← 填你的 Redis 密码
      database: 0
  # application.yml
  logging:
    level:
      com.nageoffer.shortlink.admin.remote: DEBUG
      feign: DEBUG

  feign:
    client:
      config:
        default:
          loggerLevel: FULL

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848        # 若引了 nacos-config 也关掉
management:
  health:
    nacos:
      enabled: false
short-link:
  group:
    max_num: 2
  flow-limit:
    enable: true
    time-window: 30
    max-access-count: 20