server:
  port: 8001
logging.level.org.springframework.web: DEBUG
server.error.include-message: always

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 20030106dnd    # ← 填你的 Redis 密码
      database: 0

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  cloud:
    nacos:
      discovery:
        enabled: false

short-link:
  stats:
    locale:
      amap-key: 423b8b25e4f3e7b473ab673a8ea1fa1a
  domain:
    default: nurl.ink:8001
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml